CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS party;
CREATE SCHEMA IF NOT EXISTS leads;
CREATE SCHEMA IF NOT EXISTS ops;

DO $$ BEGIN
  CREATE TYPE leads_status AS ENUM ('QDE_INIT','QDE_VALIDATED','FDE_IN_PROGRESS','FDE_COMPLETED','PREAPPROVAL_PENDING','APPROVED','REJECTED','ORDER_CREATED','DISBURSED','CANCELLED','EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS party.customer (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  mobile_no TEXT,
  email TEXT
);

CREATE TABLE IF NOT EXISTS leads.lead (
  lead_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_uuid UUID NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
  channel TEXT NOT NULL,
  origin TEXT NOT NULL,
  source_ref TEXT NOT NULL,
  merchant_code TEXT,
  customer_id BIGINT REFERENCES party.customer(customer_id),
  status leads_status NOT NULL DEFAULT 'QDE_INIT',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expired_at TIMESTAMPTZ,
  UNIQUE (origin, source_ref)
);

CREATE TABLE IF NOT EXISTS ops.outbox (
  outbox_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aggregate_type TEXT NOT NULL,
  aggregate_id BIGINT NOT NULL,
  event_type TEXT NOT NULL,
  event_key UUID NOT NULL DEFAULT uuid_generate_v4(),
  payload JSONB NOT NULL,
  headers JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  published_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS ops.idempotency (
  idempotency_key TEXT PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
