CREATE SCHEMA IF NOT EXISTS risk;
CREATE SCHEMA IF NOT EXISTS "order";

CREATE TABLE IF NOT EXISTS leads.lead_detail (
  lead_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL REFERENCES leads.lead(lead_id) ON DELETE CASCADE,
  ktp_number TEXT,
  employment_type TEXT,
  monthly_income NUMERIC(14,2),
  monthly_expense NUMERIC(14,2),
  bank_account TEXT,
  doc_flags JSONB NOT NULL DEFAULT '{}'::jsonb,
  additional_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (lead_id)
);

CREATE TABLE IF NOT EXISTS risk.scoring (
  scoring_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT NOT NULL UNIQUE REFERENCES leads.lead(lead_id) ON DELETE CASCADE,
  score NUMERIC(6,2),
  grade TEXT,
  decision TEXT,
  reason TEXT,
  raw JSONB NOT NULL DEFAULT '{}'::jsonb,
  requested_at TIMESTAMPTZ,
  responded_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS "order".agreement (
  agreement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_uuid UUID NOT NULL DEFAULT uuid_generate_v4() UNIQUE,
  lead_id BIGINT NOT NULL UNIQUE REFERENCES leads.lead(lead_id),
  agreement_no TEXT NOT NULL UNIQUE,
  approved_amount NUMERIC(14,2) NOT NULL,
  tenor SMALLINT NOT NULL,
  interest_pct NUMERIC(6,3) NOT NULL,
  installment NUMERIC(14,2) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "order".disbursement (
  disbursement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id BIGINT NOT NULL REFERENCES "order".agreement(agreement_id) ON DELETE CASCADE,
  amount NUMERIC(14,2) NOT NULL,
  channel TEXT NOT NULL,
  bank_account TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  executed_at TIMESTAMPTZ,
  UNIQUE (agreement_id)
);
